### PR TITLE
Callback fix in Symfony 31 example

### LINKED ISSUE #50: Cannot set custom callback for bugsnag
Hello, 
I installed Bugsnag successfully on my Symfony project. Bugsnag is sending me all the errors.

Now that the configuration is OK, i wanted to add a custom Callback to choose wether i should send the bug to bugsnag or not, but here is my problem :

when i add these lines to my boot() method (in AppKernel)
$bugsnag = $this->getBundle('bugsnag');
$bugsnag->registerCallback(function ($report) { ...});

I get the following error : Bundle "bugsnag" does not exist or it is not enabled, altought i registered the bundle (new Bugsnag\BugsnagBundle\BugsnagBundle(),)..
When i try $this->getBundle('BugsnagBundle') i get an error telling me the "registerCallback" method does not exists for this bundle.

Any idea on how to solve this problem ?

Thanks

### PR DESCRIPTION
**Pull request by Cawllec**
Ensures Symfony 31 example works correctly regarding callbacks.

Fixes #50

### CODE REVIEW

File: example/symfony28/app/SymfonyRequirements.php [hunk 1]
```diff
@@ -257,7 +257,7 @@ public function addPhpIniRecommendation($cfgName, $evaluation, $approveCfgAbsenc
      *
      * @param RequirementCollection $collection A RequirementCollection instance
      */
-    public function addCollection(RequirementCollection $collection)
```
Comment (snmaynard) [inline example/symfony28/app/SymfonyRequirements.php]: Why has this change been made? Surely these were autogenerated by the frameworks?

Comment (Cawllec) [reply example/symfony28/app/SymfonyRequirements.php]: I think this is a StyleCI change because the argument type is the same as the class I assume.  I don't know why it's never happened before, but can this feature to make it more readable.

Comment (GrahamCampbell) [reply example/symfony28/app/SymfonyRequirements.php]: Yes, I can confirm this change was made by StyleCI. I imagine Symfony will update it's generator to use that standard too soon, since it's code style automation tool, the same one that's ultimately used by StyleCI, enforces that change now.
